### ISSUE TITLE
fsx-sc StorageClass autoImportPolicy is not picked up FSX

### ISSUE THREAD

**Issue by antje** [kubernetes-sigs/aws-fsx-csi-driver#163]
/kind bug

**What happened?**
I'm following this example: https://github.com/kubernetes-sigs/aws-fsx-csi-driver/tree/master/examples/kubernetes/dynamic_provisioning_s3

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fsx-sc
provisioner: fsx.csi.aws.com
parameters:
  subnetId: subnet-xxx 
  securityGroupIds: sg-xxx
  autoImportPolicy: NEW
  s3ImportPath: s3://mybucket
  s3ExportPath: s3://mybucket
  deploymentType: SCRATCH_2
```
Here's my claim.yaml:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fsx-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: fsx-sc
  resources:
    requests:
      storage: 1200Gi
```

When I create the SC and PVC, I see the FSX being created in my account, but the Import preferences remains: 
Do not update my file and directory listing when objects are added to or changed in my S3 bucket.

**What you expected to happen?**

FSX to be created with the right Import Preferences. 

**How to reproduce it (as minimally and precisely as possible)?**

1/ Install EKS 1.17
2/ Installing driver via instructions: https://docs.aws.amazon.com/eks/latest/userguide/fsx-csi.html
3/ Following this example: https://github.com/kubernetes-sigs/aws-fsx-csi-driver/tree/master/examples/kubernetes/dynamic_provisioning_s3

**Anything else we need to know?**:
Tested without the `autoImportPolicy: NEW` statement in the storageclass definition. Per documentation, the FSX default should be NEW_CHANGED, but it's still showing NONE in the console. 

**Environment**
- Kubernetes version (use `kubectl version`): v1.17.9-eks-4c6976
- Driver version: v0.3.0
