### ISSUE TITLE
mount failed: File exists - Unable to mount many Lustre different mounts on one node

### ISSUE THREAD

**Issue by brettplarson** [kubernetes-sigs/aws-fsx-csi-driver#180]
/kind bug

**What happened?**
Trying to run an example test that includes 80 pods dynamically causes around 6 of them to fail with the following error in kubernetes:
```
  Warning  FailedMount        94s (x6 over 12m)   kubelet             Unable to attach or mount volumes: unmounted volumes=[persistent-storage], unattached volumes=[persistent-storage default-token-492vp]: timed out waiting for the condition
  Warning  FailedMount        37s (x15 over 15m)  kubelet             MountVolume.SetUp failed for volume "pvc-88c05a5a-645d-4038-8a8d-ec2d425dff7f" : rpc error: code = Internal desc = Could not mount "fs-00f99e4bcad7fb904.fsx.us-east-1.amazonaws.com@tcp:/rotjrbmv" at "/var/lib/kubelet/pods/1b20b217-33b2-494e-9aa6-6f4f4054a3fe/volumes/kubernetes.io~csi/pvc-88c05a5a-645d-4038-8a8d-ec2d425dff7f/mount": mount failed: exit status 17
Mounting command: mount
Mounting arguments: -t lustre fs-00f99e4bcad7fb904.fsx.us-east-1.amazonaws.com@tcp:/rotjrbmv /var/lib/kubelet/pods/1b20b217-33b2-494e-9aa6-6f4f4054a3fe/volumes/kubernetes.io~csi/pvc-88c05a5a-645d-4038-8a8d-ec2d425dff7f/mount
Output: mount.lustre: mount fs-00f99e4bcad7fb904.fsx.us-east-1.amazonaws.com@tcp:/rotjrbmv at /var/lib/kubelet/pods/1b20b217-33b2-494e-9aa6-6f4f4054a3fe/volumes/kubernetes.io~csi/pvc-88c05a5a-645d-4038-8a8d-ec2d425dff7f/mount failed: File exists
```
The 6 pods that aren't working stay pending and do not start:
![image](https://user-images.githubusercontent.com/33815371/114910129-2511e980-9de3-11eb-995d-fe5d8e913d79.png)

The following error was posted in the Node's kernel:

```
E0415 16:59:21.020036    7921 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/csi/fsx.csi.aws.com^fs-02505a5fb635d078c podName: nodeName:}" failed. No retries permitt
ed until 2021-04-15 17:01:23.019999837 +0000 UTC m=+1916.131202671 (durationBeforeRetry 2m2s). Error: "MountVolume.SetUp failed for volume \"pvc-5be9aa5e-a0ad-4a5b-bc69-4ee8bf5ed486\" (Unique
Name: \"kubernetes.io/csi/fsx.csi.aws.com^fs-02505a5fb635d078c\") pod \"fsx-app-63\" (UID: \"c40af3b4-3ead-4800-9600-81699266812e\") : rpc error: code = Internal desc = Could not mount \"fs-0
2505a5fb635d078c.fsx.us-east-1.amazonaws.com@tcp:/qgtjrbmv\" at \"/var/lib/kubelet/pods/c40af3b4-3ead-4800-9600-81699266812e/volumes/kubernetes.io~csi/pvc-5be9aa5e-a0ad-4a5b-bc69-4ee8bf5ed486
/mount\": mount failed: exit status 17\nMounting command: mount\nMounting arguments: -t lustre fs-02505a5fb635d078c.fsx.us-east-1.amazonaws.com@tcp:/qgtjrbmv /var/lib/kubelet/pods/c40af3b4-3e
ad-4800-9600-81699266812e/volumes/kubernetes.io~csi/pvc-5be9aa5e-a0ad-4a5b-bc69-4ee8bf5ed486/mount\nOutput: mount.lustre: mount fs-02505a5fb635d078c.fsx.us-east-1.amazonaws.com@tcp:/qgtjrbmv 
at /var/lib/kubelet/pods/c40af3b4-3ead-4800-9600-81699266812e/volumes/kubernetes.io~csi/pvc-5be9aa5e-a0ad-4a5b-bc69-4ee8bf5ed486/mount failed: File exists\n"
I0415 16:59:22.110346    7921 setters.go:77] Using node IP: "172.31.225.81"
{"level":"info","ts":"2021-04-15T16:59:22.587Z","caller":"/usr/local/go/src/runtime/proc.go:203","msg":"CNI Plugin version: v1.7.5 ..."}
{"level":"info","ts":"2021-04-15T16:59:27.598Z","caller":"/usr/local/go/src/runtime/proc.go:203","msg":"CNI Plugin version: v1.7.5 ..."}
I0415 16:59:29.631090    7921 reconciler.go:269] operationExecutor.MountVolume started for volume "pvc-0fc60f2b-ab5d-4583-8704-4530e4741dd9" (UniqueName: "kubernetes.io/csi/fsx.csi.aws.com^fs
-01d565b67eb62b2c9") pod "fsx-app-73" (UID: "ad1b440f-e605-4204-a0c5-5f77880e0418")
I0415 16:59:29.632224    7921 csi_attacher.go:336] kubernetes.io/csi: attacher.MountDevice STAGE_UNSTAGE_VOLUME capability not set. Skipping MountDevice...
I0415 16:59:29.632249    7921 operation_generator.go:596] MountVolume.MountDevice succeeded for volume "pvc-0fc60f2b-ab5d-4583-8704-4530e4741dd9" (UniqueName: "kubernetes.io/csi/fsx.csi.aws.c
om^fs-01d565b67eb62b2c9") pod "fsx-app-73" (UID: "ad1b440f-e605-4204-a0c5-5f77880e0418") device mount path "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-0fc60f2b-ab5d-4583-8704-4530e4741
dd9/globalmount"
sysfs: cannot create duplicate filename '/dev/char/10:1'
CPU: 15 PID: 9215 Comm: llog_process_th Tainted: P         C  E     5.4.95-42.163.amzn2.x86_64 #1
Hardware name: Amazon EC2 r5.4xlarge/, BIOS 1.0 10/16/2017
Call Trace:
 dump_stack+0x66/0x81
 sysfs_warn_dup+0x56/0x70
 sysfs_do_create_link_sd.isra.2+0xa6/0xc0
 device_add+0x5bd/0x680
 device_create_groups_vargs+0xd6/0xe0
 device_create_with_groups+0x3f/0x60
 ? snprintf+0x45/0x70
 misc_register+0x155/0x190
 mdc_changelog_cdev_init+0x3d0/0x580 [mdc]
 ? __llog_ctxt_put+0x2b/0x140 [obdclass]
 mdc_setup+0x203/0x5c0 [mdc]
 obd_setup+0x1bb/0x270 [obdclass]
 ? cfs_hash_create+0x394/0x8c0 [libcfs]
 class_setup+0x41d/0x7d0 [obdclass]
 class_process_config+0x18ba/0x23d0 [obdclass]
 ? libcfs_debug_msg+0x50/0x70 [libcfs]
 ? libcfs_debug_msg+0x50/0x70 [libcfs]
 class_config_llog_handler+0x78e/0x13b0 [obdclass]
 llog_process_thread+0x606/0x1470 [obdclass]
 ? llog_backup+0x4c0/0x4c0 [obdclass]
 llog_process_thread_daemonize+0x96/0xd0 [obdclass]
 kthread+0x113/0x130
 ? kthread_park+0x90/0x90
 ret_from_fork+0x35/0x40
Lustre:    cmd=cf003 0:twtjrbmv-MDT0000-mdc  1:twtjrbmv-MDT0000_UUID  2:198.19.20.249@tcp1  
```

**What you expected to happen?**
This should mount properly.

**How to reproduce it (as minimally and precisely as possible)?**
Create 80 different pods based off of the dynamic example. I use a helm chart based on the example to deploy this over and over again.
Ie.

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fsx-claim-dyn-{{ .Release.Name }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: fsx-sc
  resources:
    requests:
      storage: 1200Gi
```
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: fsx-app-{{ .Release.Name }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  containers:
  - name: app
    image: ourprivateecrhere/base_ubuntu16.04:developlatest
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: fsx-claim-dyn-{{ .Release.Name }}
```
I then created different releases named 1, 2, etc. until 80 - the code below is Fish shell, but it should be similar in bash.
```
for x in (seq 80) 
      helm upgrade -i $x .
  end
```

**Anything else we need to know?**:
We are evaluating using Lustre in EKS, but I've run into this issue multiple times when testing. It may be simply because these pods are all clumped on one node, which maybe isn't a use case we would see in production due to the pods sizes being larger for data science workloads. One other note is our nodes are using the NG kernel version: `5.4.95-42.163.amzn2.x86_64`.

**Environment**
- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Driver version:
```
aws-fsx-csi-driver:v0.3.0
```
