### ISSUE TITLE
extraTags not working

### ISSUE THREAD

**Issue by vale21** [kubernetes-sigs/aws-fsx-csi-driver#273]
/kind bug

**What happened?**

I am configuring extraTags in the my Storage class, following the sample code of this repo:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lustre
allowVolumeExpansion: true
allowedTopologies: []
mountOptions:
  - flock
  - user_xattr
parameters:
  dataCompressionType: LZ4
  deploymentType: PERSISTENT_2
  extraTags: Tag1=Value1,Tag2=Value2
  fileSystemTypeVersion: '2.12'
  perUnitStorageThroughput: '1000'
  securityGroupIds: sg-***
  subnetId: subnet-***
provisioner: fsx.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

**What you expected to happen?**

I was expecting to see the 2 extra tags being applied to the automatically provisioned fsx file system. Instead, they are not there:
```
$ aws fsx describe-file-systems --file-system-ids fs-062fc8a4904f*****
{
    "FileSystems": [
        {
            "OwnerId": "***",
            "CreationTime": "***",
            "FileSystemId": "fs-062fc8a4904f*****",
            "FileSystemType": "LUSTRE",
            "Lifecycle": "AVAILABLE",
            "StorageCapacity": 1200,
            "StorageType": "SSD",
            "VpcId": "vpc-***",
            "SubnetIds": [
                "subnet-***"
            ],
            "NetworkInterfaceIds": [
                "eni-***",
                "eni-***"
            ],
            "DNSName": "fs-062fc8a4904f*****.fsx.***.amazonaws.com",
            "KmsKeyId": "arn:aws:kms***",
            "ResourceARN": "arn:aws:fsx:***",
            "Tags": [
                {
                    "Key": "CSIVolumeName",
                    "Value": "pvc-***"
                }
            ],
            "LustreConfiguration": {
                "WeeklyMaintenanceStartTime": "2:22:00",
                "DeploymentType": "PERSISTENT_2",
                "PerUnitStorageThroughput": 1000,
                "MountName": "aupibbmv",
                "CopyTagsToBackups": false,
                "DataCompressionType": "LZ4",
                "LogConfiguration": {
                    "Level": "DISABLED"
                }
            },
            "FileSystemTypeVersion": "2.12"
        }
    ]
}
```

**How to reproduce it (as minimally and precisely as possible)?**

Deploy the storage class above in EKS and craete a container that provisions a PVC using that Storage Class

**Anything else we need to know?**:

**Environment**
- EKS
- Kubernetes version (use `kubectl version`): v1.22.15-eks-fb459a0
- Driver version:  helm chart v1.4.4, app v0.8.3
