### ISSUE TITLE
Sample pod stuck in `ContainerCreating` on bottlerocket cluster

### ISSUE THREAD

**Issue by jpmcb** [kubernetes-sigs/aws-fsx-csi-driver#289]
/kind bug

**What happened?**

Hello from the bottlerocket team! 👋🏼 I followed the steps in [the AWS FSx driver tutorial ](https://docs.aws.amazon.com/eks/latest/userguide/fsx-csi.html) using `--node-ami-type bottlerocket` for cluster creation and I get the following events when deploying the sample pod:

```
Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    5m40s                 default-scheduler  Successfully assigned default/fsx-app to ip-192-168-90-119.us-west-2.compute.internal
  Warning  FailedMount  90s (x10 over 5m40s)  kubelet            MountVolume.SetUp failed for volume "pvc-3152d44d-c864-4d48-bdc0-a56add8e717f" : rpc error: code = Internal desc = Could not mount "fs-08a962c9c8001462f.fsx.us-west-2.amazonaws.com@tcp:/aqhs7bev" at "/var/lib/kubelet/pods/1953ad56-e8c1-48f2-9762-64fe0a5d16df/volumes/kubernetes.io~csi/pvc-3152d44d-c864-4d48-bdc0-a56add8e717f/mount": mount failed: exit status 19
Mounting command: mount
Mounting arguments: -t lustre -o flock fs-08a962c9c8001462f.fsx.us-west-2.amazonaws.com@tcp:/aqhs7bev /var/lib/kubelet/pods/1953ad56-e8c1-48f2-9762-64fe0a5d16df/volumes/kubernetes.io~csi/pvc-3152d44d-c864-4d48-bdc0-a56add8e717f/mount
Output: mount.lustre: mount fs-08a962c9c8001462f.fsx.us-west-2.amazonaws.com@tcp:/aqhs7bev at /var/lib/kubelet/pods/1953ad56-e8c1-48f2-9762-64fe0a5d16df/volumes/kubernetes.io~csi/pvc-3152d44d-c864-4d48-bdc0-a56add8e717f/mount failed: No such device
Are the lustre modules loaded?
Check /etc/modprobe.conf and /proc/filesystems
  Warning  FailedMount  80s (x2 over 3m37s)  kubelet  Unable to attach or mount volumes: unmounted volumes=[persistent-storage], unattached volumes=[persistent-storage kube-api-access-wlm48]: timed out waiting for the condition
``` 

**What you expected to happen?**

Following the tutorial, everything was fine but the sample pod deployment doesn't come up. Would expect the pod to work out of the box. Am I missing something? The other resources deployed in the tutorial seem fine:

```
❯ k get storageclasses
NAME            PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
fsx-sc          fsx.csi.aws.com         Delete          Immediate              false                  23m
gp2 (default)   kubernetes.io/aws-ebs   Delete          WaitForFirstConsumer   false                  41m
```

```
❯ k get pvc/fsx-claim
NAME        STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
fsx-claim   Bound    pvc-3152d44d-c864-4d48-bdc0-a56add8e717f   1200Gi     RWX            fsx-sc         22m
```

**How to reproduce it (as minimally and precisely as possible)?**

Follow the AWS FSx csi driver tutorial with the following modification when deploying a cluster using `eksctl`:

```
eksctl create cluster \
    --name my-csi-fsx-cluster \
    --version 1.24 \
    --region us-west-2 \
    --with-oidc \
    --ssh-access \
    --ssh-public-key my-keys \
    --nodegroup-name my-ng \
    --node-ami-family bottlerocket \
    --node-type c5.xlarge
```

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
This is on a new 1.24 EKS cluster using bottlerocket nodes (where this issue originallu surfaced: https://github.com/bottlerocket-os/bottlerocket/issues/2685)
```
❯ k version --output=yaml
clientVersion:
  buildDate: "2022-09-21T14:33:49Z"
  compiler: gc
  gitCommit: 5835544ca568b757a8ecae5c153f317e5736700e
  gitTreeState: clean
  gitVersion: v1.25.2
  goVersion: go1.19.1
  major: "1"
  minor: "25"
  platform: linux/amd64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2022-11-29T18:45:03Z"
  compiler: gc
  gitCommit: abb98ec0631dfe573ec5eae40dc48fd8f2017424
  gitTreeState: clean
  gitVersion: v1.24.8-eks-ffeb93d
  goVersion: go1.18.8
  major: "1"
  minor: 24+
  platform: linux/amd64
```

- Driver version:

```
kubectl apply -k "github.com/kubernetes-sigs/aws-fsx-csi-driver/deploy/kubernetes/overlays/stable/?ref=master"
```
