### ISSUE TITLE
Controller is being evicted every 5 minutes 

### ISSUE THREAD

**Issue by BEvgeniyS** [kubernetes-sigs/aws-fsx-csi-driver#305]
/kind bug

**What happened?**
Controller is being evicted every 5 minutes 

**What you expected to happen?**
If I set  
```
  nodeSelector:
    mynodetype: "true"

  tolerations:
  - effect: NoExecute
    key: mynodetype
    operator: Equal
    value: "false"
```
in values.yaml, I expect the controller to run on the node without being evicted every 5 minutes

**How to reproduce it (as minimally and precisely as possible)?**
- Have a node with taint:
  ```  - effect: NoExecute                                                                                                                                                                                     
    key: mynodetype                                                                                        
    value: "false"
  ```
- set the nodeSelector and toleration for the Controller in values.yaml:
  ```
  nodeSelector:
    mynodetype: "true"

  tolerations:
  - effect: NoExecute
    key: mynodetype
    operator: Equal
    value: "false"
  ```

**Anything else we need to know?**:
K8s will only apply first matched toleration. So the order of toleration matters, especially when there's `tolerationSeconds` involved. Universal timed `NoExecute` [toleration](https://github.com/kubernetes-sigs/aws-fsx-csi-driver/blob/511427dbc5d931dcd03729d98755b61a601560c8/charts/aws-fsx-csi-driver/templates/controller-deployment.yaml#L40)
```
- operator: Exists
  effect: NoExecute
  tolerationSeconds: 300
```

 makes it impossible to meaningfully use other NoExecute tolerations because it's hardcoded to be on the top. Moving it to below configured values solves the issues for us.

**Environment**
- Kubernetes version (use `kubectl version`): v1.24.10-eks-48e63af
- Driver version: v0.8.3
