### ISSUE TITLE
Question: Support templating extraTags value

### ISSUE THREAD

**Issue by DevSusu** [kubernetes-sigs/aws-fsx-csi-driver#329]
Hello, I'm considering FSx for storage in EKS cluster.

Been using default EBS driver, which supports templating tags like below
As FSx volume heavier in costs, we need this tags to Seperate Costs by namespace, tenant, ...

https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/tagging.md
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
parameters:
  tagSpecification_1: "pvcnamespace={{ .PVCNamespace }}"
  tagSpecification_2: "pvcname={{ .PVCName }}"
  tagSpecification_3: "pvname={{ .PVName }}"
```

As per FSx driver docs, it seems only fixed strings can be given, is it correct?
If yes, do you have plans to Support this feature?(templating Tags values, based on PV/PVC resource)

https://github.com/kubernetes-sigs/aws-fsx-csi-driver/blob/master/examples/kubernetes/dynamic_provisioning/README.md
```
extraTags (Optional) - Tags that will be set on the FSx resource created in AWS, in the form of a comma separated list with each tag delimited by an equals sign (example - "Tag1=Value1,Tag2=Value2") . Default is a single tag with CSIVolumeName as the key and the generated volume name as it's value.
```

/triage support
