### ISSUE TITLE
Supporting (multiple) data repository association

### ISSUE THREAD

**Issue by everpeace** [kubernetes-sigs/aws-fsx-csi-driver#367]
**Is your feature request related to a problem?/Why is this needed**

We would like to create `PERSISTENT_2` deployment type FSx volumes with (multiple) data repository associations via the kubernetes CSI. 

Currently, this driver only supports [CreateFileSystemLustreConfiguration.Auto{Import,Export}Path](https://docs.aws.amazon.com/fsx/latest/APIReference/API_CreateFileSystemLustreConfiguration.html) based configuration to link S3 bucket. But, this is not supported by `PERSISTENT_2` deployment type. `PERSISTENT_2` only supports [Data Repository Associations](https://docs.aws.amazon.com/fsx/latest/APIReference/API_DataRepositoryAssociation.html) to link S3 buckets.  Thus, we can currently create `PERSISTENT_2` filesystems with this driver but no buckets can be linked to the filesystems.

/feature

**Describe the solution you'd like in detail**

As describe in https://github.com/kubernetes-sigs/aws-fsx-csi-driver/issues/252#issuecomment-1371774954:

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fsx-sc
provisioner: fsx.csi.aws.com
parameters:
  subnetId: <subnet-id>
  securityGroupIds: <security-group-id>
  deploymentType: PERSISTENT_2
  dataRepositories: |
    - fileSystemPath: /ns1/path1
      dataRepositoryPath: s3://s3-path-1
      BatchImportMetaDataOnCreate: true
    - fileSystemPath: /ns1/path2
      dataRepositoryPath: s3://s3-path-2
      BatchImportMetaDataOnCreate: true
```

**Additional context**

I'm a colleague with @ittus.  
I open this issue as instructed in https://github.com/kubernetes-sigs/aws-fsx-csi-driver/issues/252#issuecomment-1381023146
