### ISSUE TITLE
Dynamic PERSISTENT_2 volume provisioning with S3 DRA is not supported

### ISSUE THREAD

**Issue by psnilesh** [kubernetes-sigs/aws-fsx-csi-driver#412]
/kind bug

**What happened?**  When creating a `persistent_2` filesystem with `s3Import` and `s3Export` path, you get below error
```
CreateFileSystem failed: operation error FSx: CreateFileSystem, https response error StatusCode: 400, RequestID: baec687b-725f-42a6-9638-68b33119912b, BadRequest: Linking a Persistent 2 file system to an S3 bucket using the LustreConfiguration is not supported. Create a file system and then create a data repository association to link S3 buckets to the file system. For more details, visit https://docs.aws.amazon.com/fsx/latest/LustreGuide/create-dra-linked-data-repo.html
```

**What you expected to happen?** I was expecting the fs to be created successfully along with necessary DRA assocations.

**How to reproduce it (as minimally and precisely as possible)?**
```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fsx-sc
provisioner: fsx.csi.aws.com
parameters:
  subnetId: <my-private-subnet>
  securityGroupIds: <my-sg-id>
  autoImportPolicy: NONE
  s3ImportPath: s3://<my-test-bucket-name>/import
  s3ExportPath: s3://<my-test-bucket-name>/export
  deploymentType: PERSISTENT_2
  perUnitStorageThroughput: "250"
  dataCompressionType: LZ4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fsx-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: fsx-sc
  resources:
    requests:
      storage: 1200Gi
```

**Anything else we need to know?**:
I know the error is coming from `CreateFileSystem` API, but I was surprised FSx controller doesn't create an empty file system first and then DRA using [CreateDataRepositoryAssociation](https://docs.aws.amazon.com/fsx/latest/APIReference/API_CreateDataRepositoryAssociation.html) API before marking volume as ready/consumable.  

**Environment**
- Kubernetes version (use `kubectl version`):v1.32.2
- Driver version: latest
