### ISSUE TITLE
Dynamic provision doesn't support more subnets

### ISSUE THREAD

**Issue by Jeffwan** [kubernetes-sigs/aws-fsx-csi-driver#47]
**What happened?**
```
  Warning    ProvisioningFailed    7s    fsx.csi.aws.com_fsx-csi-controller-0_0d924577-4c05-11e9-8258-9298fcb694b4  failed to provision volume with StorageClass "fsx-sc": rpc error: code = Internal desc = Could not create volume "pvc-1ad68536-4c05-11e9-8a3f-0a169557a7b4": CreateFileSystem failed: BadRequest: 1 validation error detected: Value '[subnet-02dd4dbb726318783,subnet-05a291af34a4215e4,subnet-0e4121bf71352369c,subnet-0f4c76eabb0bef2f6,subnet-00fbb4354a2f78801,subnet-0dd49959579368dc2]' at 'subnetIds' failed to satisfy constraint: Member must satisfy constraint: [Member must have length less than or equal to 24, Member must have length greater than or equal to 15, Member must satisfy regular expression pattern: ^(subnet-[0-9a-f]{8,})$]
             status code: 400, request id: 1460fc50-593f-4f32-af2b-baef539109a1
```

**What you expected to happen?**
Can not attach multiple subnets

**How to reproduce it (as minimally and precisely as possible)?**

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fsx-sc
provisioner: fsx.csi.aws.com
parameters:
  subnetId: subnet-02dd4dbb726318783,subnet-05a291af34a4215e4,subnet-0e4121bf71352369c,subnet-0f4c76eabb0bef2f6,subnet-00fbb4354a2f78801,subnet-0dd49959579368dc2
  securityGroupIds: sg-069230325a57c415e

```

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): 1.11
- Driver version: 18.06
